#include "src/game/envfx_snow.h"

const GeoLayout kaguraoutfit1_2_LoD_Switch_opt0_Cap_Effect_Switch_opt0_Hatless_Switch_opt1_Eye_Material_Switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_ALPHA, kaguraoutfit1_Switch_Option_Head_Capless_DL_mesh_layer_4_mat_override_eyes_half_closed_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kaguraoutfit1_Switch_Option_Head_Capless_DL_mesh_layer_1_mat_override_eyes_half_closed_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kaguraoutfit1_2_LoD_Switch_opt0_Cap_Effect_Switch_opt0_Hatless_Switch_opt1_Eye_Material_Switch_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_ALPHA, kaguraoutfit1_Switch_Option_Head_Capless_DL_mesh_layer_4_mat_override_eyes_closed_2),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kaguraoutfit1_Switch_Option_Head_Capless_DL_mesh_layer_1_mat_override_eyes_closed_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kaguraoutfit1_2_LoD_Switch_opt0_Cap_Effect_Switch_opt0_Hatless_Switch_opt1_Eye_Material_Switch_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_ALPHA, kaguraoutfit1_Switch_Option_Head_Capless_DL_mesh_layer_4_mat_override_eyes_closed_2),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kaguraoutfit1_Switch_Option_Head_Capless_DL_mesh_layer_1_mat_override_eyes_closed_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kaguraoutfit1_2_LoD_Switch_opt0_Cap_Effect_Switch_opt0_Hatless_Switch_opt1_Eye_Material_Switch_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_ALPHA, kaguraoutfit1_Switch_Option_Head_Capless_DL_mesh_layer_4_mat_override_eyes_closed_2),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kaguraoutfit1_Switch_Option_Head_Capless_DL_mesh_layer_1_mat_override_eyes_closed_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kaguraoutfit1_2_LoD_Switch_opt0_Cap_Effect_Switch_opt0_Hatless_Switch_opt1_Eye_Material_Switch_opt5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_ALPHA, kaguraoutfit1_Switch_Option_Head_Capless_DL_mesh_layer_4_mat_override_eyes_closed_2),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kaguraoutfit1_Switch_Option_Head_Capless_DL_mesh_layer_1_mat_override_eyes_closed_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kaguraoutfit1_2_LoD_Switch_opt0_Cap_Effect_Switch_opt0_Hatless_Switch_opt1_Eye_Material_Switch_opt6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_ALPHA, kaguraoutfit1_Switch_Option_Head_Capless_DL_mesh_layer_4_mat_override_eyes_closed_2),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kaguraoutfit1_Switch_Option_Head_Capless_DL_mesh_layer_1_mat_override_eyes_closed_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kaguraoutfit1_2_LoD_Switch_opt0_Cap_Effect_Switch_opt0_Hatless_Switch_opt1_Eye_Material_Switch_opt7[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_ALPHA, kaguraoutfit1_Switch_Option_Head_Capless_DL_mesh_layer_4_mat_override_eyes_dead_3),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kaguraoutfit1_Switch_Option_Head_Capless_DL_mesh_layer_1_mat_override_eyes_dead_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kaguraoutfit1_Mario_Cap_Off_Armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_ALPHA, kaguraoutfit1_Switch_Option_Head_Capless_DL_mesh_layer_4),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, kaguraoutfit1_Switch_Option_Head_Capless_DL_mesh_layer_1),
			GEO_CLOSE_NODE(),
			GEO_BRANCH(1, kaguraoutfit1_2_LoD_Switch_opt0_Cap_Effect_Switch_opt0_Hatless_Switch_opt1_Eye_Material_Switch_opt1),
			GEO_BRANCH(1, kaguraoutfit1_2_LoD_Switch_opt0_Cap_Effect_Switch_opt0_Hatless_Switch_opt1_Eye_Material_Switch_opt2),
			GEO_BRANCH(1, kaguraoutfit1_2_LoD_Switch_opt0_Cap_Effect_Switch_opt0_Hatless_Switch_opt1_Eye_Material_Switch_opt3),
			GEO_BRANCH(1, kaguraoutfit1_2_LoD_Switch_opt0_Cap_Effect_Switch_opt0_Hatless_Switch_opt1_Eye_Material_Switch_opt4),
			GEO_BRANCH(1, kaguraoutfit1_2_LoD_Switch_opt0_Cap_Effect_Switch_opt0_Hatless_Switch_opt1_Eye_Material_Switch_opt5),
			GEO_BRANCH(1, kaguraoutfit1_2_LoD_Switch_opt0_Cap_Effect_Switch_opt0_Hatless_Switch_opt1_Eye_Material_Switch_opt6),
			GEO_BRANCH(1, kaguraoutfit1_2_LoD_Switch_opt0_Cap_Effect_Switch_opt0_Hatless_Switch_opt1_Eye_Material_Switch_opt7),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kaguraoutfit1_Mario_Left_Hand_Open_Armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_ALPHA, 60, 0, 0, kaguraoutfit1_Switch_Option_Left_Hand_Open_mesh_layer_4),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kaguraoutfit1_Mario_Right_Hand_Open_Armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_ALPHA, 60, 0, 0, kaguraoutfit1_Switch_Option_Right_Hand_Open_mesh_layer_4),
		GEO_OPEN_NODE(),
			GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kaguraoutfit1_Mario_Right_Hand_Peace_Armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_ALPHA, 60, 0, 0, kaguraoutfit1_Switch_Option_Right_Hand_Peace_mesh_layer_4),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kaguraoutfit1_Mario_Right_Hand_Cap_M_Logo_Armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, kaguraoutfit1_Switch_Option_Right_Hand_Cap_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_ALPHA, kaguraoutfit1_Switch_Option_Right_Hand_Cap_mesh_layer_4),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kaguraoutfit1_Mario_Right_Hand_Wing_Cap_Armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, kaguraoutfit1_Switch_Option_Right_Hand_Wing_Cap_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_ALPHA, kaguraoutfit1_Switch_Option_Right_Hand_Wing_Cap_mesh_layer_4),
			GEO_DISPLAY_LIST(LAYER_ALPHA, kaguraoutfit1_Switch_Option_Right_Hand_Wing_Cap_Wings_mesh_layer_4),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kaguraoutfit1_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1_Hatless_Switch_opt1_Eye_Material_Switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kaguraoutfit1_Switch_Option_Head_Capless_DL_mesh_layer_4_mat_override_eyes_half_closed_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kaguraoutfit1_Switch_Option_Head_Capless_DL_mesh_layer_1_mat_override_eyes_half_closed_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kaguraoutfit1_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1_Hatless_Switch_opt1_Eye_Material_Switch_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kaguraoutfit1_Switch_Option_Head_Capless_DL_mesh_layer_4_mat_override_eyes_closed_2),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kaguraoutfit1_Switch_Option_Head_Capless_DL_mesh_layer_1_mat_override_eyes_closed_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kaguraoutfit1_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1_Hatless_Switch_opt1_Eye_Material_Switch_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kaguraoutfit1_Switch_Option_Head_Capless_DL_mesh_layer_4_mat_override_eyes_closed_2),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kaguraoutfit1_Switch_Option_Head_Capless_DL_mesh_layer_1_mat_override_eyes_closed_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kaguraoutfit1_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1_Hatless_Switch_opt1_Eye_Material_Switch_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kaguraoutfit1_Switch_Option_Head_Capless_DL_mesh_layer_4_mat_override_eyes_closed_2),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kaguraoutfit1_Switch_Option_Head_Capless_DL_mesh_layer_1_mat_override_eyes_closed_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kaguraoutfit1_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1_Hatless_Switch_opt1_Eye_Material_Switch_opt5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kaguraoutfit1_Switch_Option_Head_Capless_DL_mesh_layer_4_mat_override_eyes_closed_2),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kaguraoutfit1_Switch_Option_Head_Capless_DL_mesh_layer_1_mat_override_eyes_closed_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kaguraoutfit1_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1_Hatless_Switch_opt1_Eye_Material_Switch_opt6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kaguraoutfit1_Switch_Option_Head_Capless_DL_mesh_layer_4_mat_override_eyes_closed_2),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kaguraoutfit1_Switch_Option_Head_Capless_DL_mesh_layer_1_mat_override_eyes_closed_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kaguraoutfit1_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1_Hatless_Switch_opt1_Eye_Material_Switch_opt7[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kaguraoutfit1_Switch_Option_Head_Capless_DL_mesh_layer_4_mat_override_eyes_dead_3),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kaguraoutfit1_Switch_Option_Head_Capless_DL_mesh_layer_1_mat_override_eyes_dead_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kaguraoutfit1_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1_jump_kaguraoutfit1_Mario_Cap_Off_Armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kaguraoutfit1_Switch_Option_Head_Capless_DL_mesh_layer_4),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kaguraoutfit1_Switch_Option_Head_Capless_DL_mesh_layer_1),
			GEO_CLOSE_NODE(),
			GEO_BRANCH(1, kaguraoutfit1_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1_Hatless_Switch_opt1_Eye_Material_Switch_opt1),
			GEO_BRANCH(1, kaguraoutfit1_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1_Hatless_Switch_opt1_Eye_Material_Switch_opt2),
			GEO_BRANCH(1, kaguraoutfit1_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1_Hatless_Switch_opt1_Eye_Material_Switch_opt3),
			GEO_BRANCH(1, kaguraoutfit1_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1_Hatless_Switch_opt1_Eye_Material_Switch_opt4),
			GEO_BRANCH(1, kaguraoutfit1_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1_Hatless_Switch_opt1_Eye_Material_Switch_opt5),
			GEO_BRANCH(1, kaguraoutfit1_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1_Hatless_Switch_opt1_Eye_Material_Switch_opt6),
			GEO_BRANCH(1, kaguraoutfit1_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1_Hatless_Switch_opt1_Eye_Material_Switch_opt7),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kaguraoutfit1_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1_jump_kaguraoutfit1_Mario_Left_Hand_Open_Armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, kaguraoutfit1_Switch_Option_Left_Hand_Open_mesh_layer_4),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kaguraoutfit1_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1_jump_kaguraoutfit1_Mario_Right_Hand_Open_Armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, kaguraoutfit1_Switch_Option_Right_Hand_Open_mesh_layer_4),
		GEO_OPEN_NODE(),
			GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kaguraoutfit1_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1_jump_kaguraoutfit1_Mario_Right_Hand_Peace_Armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, kaguraoutfit1_Switch_Option_Right_Hand_Peace_mesh_layer_4),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kaguraoutfit1_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1_jump_kaguraoutfit1_Mario_Right_Hand_Cap_M_Logo_Armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, kaguraoutfit1_Switch_Option_Right_Hand_Cap_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kaguraoutfit1_Switch_Option_Right_Hand_Cap_mesh_layer_4),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kaguraoutfit1_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1_jump_kaguraoutfit1_Mario_Right_Hand_Wing_Cap_Armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, kaguraoutfit1_Switch_Option_Right_Hand_Wing_Cap_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kaguraoutfit1_Switch_Option_Right_Hand_Wing_Cap_mesh_layer_4),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kaguraoutfit1_Switch_Option_Right_Hand_Wing_Cap_Wings_mesh_layer_4),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kaguraoutfit1_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1_Hatless_Switch_opt0_Eye_Material_Switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kaguraoutfit1_Head_DL_mesh_layer_4_mat_override_eyes_half_closed_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kaguraoutfit1_Head_DL_mesh_layer_1_mat_override_eyes_half_closed_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kaguraoutfit1_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1_Hatless_Switch_opt0_Eye_Material_Switch_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kaguraoutfit1_Head_DL_mesh_layer_4_mat_override_eyes_closed_2),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kaguraoutfit1_Head_DL_mesh_layer_1_mat_override_eyes_closed_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kaguraoutfit1_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1_Hatless_Switch_opt0_Eye_Material_Switch_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kaguraoutfit1_Head_DL_mesh_layer_4_mat_override_eyes_right_3),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kaguraoutfit1_Head_DL_mesh_layer_1_mat_override_eyes_right_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kaguraoutfit1_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1_Hatless_Switch_opt0_Eye_Material_Switch_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kaguraoutfit1_Head_DL_mesh_layer_4_mat_override_eyes_left_4),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kaguraoutfit1_Head_DL_mesh_layer_1_mat_override_eyes_left_4),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kaguraoutfit1_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1_Hatless_Switch_opt0_Eye_Material_Switch_opt5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kaguraoutfit1_Head_DL_mesh_layer_4_mat_override_eyes_up_5),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kaguraoutfit1_Head_DL_mesh_layer_1_mat_override_eyes_up_5),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kaguraoutfit1_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1_Hatless_Switch_opt0_Eye_Material_Switch_opt6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kaguraoutfit1_Head_DL_mesh_layer_4_mat_override_eyes_down_6),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kaguraoutfit1_Head_DL_mesh_layer_1_mat_override_eyes_down_6),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kaguraoutfit1_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1_Hatless_Switch_opt0_Eye_Material_Switch_opt7[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kaguraoutfit1_Head_DL_mesh_layer_4_mat_override_eyes_dead_7),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kaguraoutfit1_Head_DL_mesh_layer_1_mat_override_eyes_dead_7),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kaguraoutfit1_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, kaguraoutfit1_Butt_mesh_layer_4),
			GEO_OPEN_NODE(),
				GEO_ASM(0, geo_move_mario_part_from_parent),
				GEO_ASM(0, geo_mario_tilt_torso),
				GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 68, 0, 0, kaguraoutfit1_Torso_mesh_layer_4),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 87, 0, 0, NULL),
						GEO_OPEN_NODE(),
							GEO_ASM(0, geo_mario_head_rotation),
							GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
							GEO_OPEN_NODE(),
								GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
								GEO_OPEN_NODE(),
									GEO_NODE_START(),
									GEO_OPEN_NODE(),
										GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kaguraoutfit1_Head_DL_mesh_layer_4),
												GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kaguraoutfit1_Head_DL_mesh_layer_1),
											GEO_CLOSE_NODE(),
											GEO_BRANCH(1, kaguraoutfit1_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1_Hatless_Switch_opt0_Eye_Material_Switch_opt1),
											GEO_BRANCH(1, kaguraoutfit1_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1_Hatless_Switch_opt0_Eye_Material_Switch_opt2),
											GEO_BRANCH(1, kaguraoutfit1_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1_Hatless_Switch_opt0_Eye_Material_Switch_opt3),
											GEO_BRANCH(1, kaguraoutfit1_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1_Hatless_Switch_opt0_Eye_Material_Switch_opt4),
											GEO_BRANCH(1, kaguraoutfit1_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1_Hatless_Switch_opt0_Eye_Material_Switch_opt5),
											GEO_BRANCH(1, kaguraoutfit1_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1_Hatless_Switch_opt0_Eye_Material_Switch_opt6),
											GEO_BRANCH(1, kaguraoutfit1_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1_Hatless_Switch_opt0_Eye_Material_Switch_opt7),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
									GEO_BRANCH(1, kaguraoutfit1_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1_jump_kaguraoutfit1_Mario_Cap_Off_Armature),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_FORCE, 142, -51, 126, -15, 33, -133),
								GEO_OPEN_NODE(),
									GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
									GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kaguraoutfit1_Left_Wing_DL_mesh_layer_4),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_FORCE, 142, -51, -126, 15, -33, -133),
								GEO_OPEN_NODE(),
									GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
									GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kaguraoutfit1_Right_Wing_DL_mesh_layer_4),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 67, -10, 79, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, kaguraoutfit1_Left_Arm_Color_mesh_layer_4),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 65, 0, 0, kaguraoutfit1_Left_Forearm_mesh_layer_4),
								GEO_OPEN_NODE(),
									GEO_SWITCH_CASE(1, geo_switch_mario_hand),
									GEO_OPEN_NODE(),
										GEO_NODE_START(),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_ASM(1, geo_mario_hand_foot_scaler),
												GEO_SCALE(LAYER_FORCE, 65536),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kaguraoutfit1_Left_Hand_DL_mesh_layer_4),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_BRANCH(1, kaguraoutfit1_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1_jump_kaguraoutfit1_Mario_Left_Hand_Open_Armature),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 68, -10, -79, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, kaguraoutfit1_Right_Arm_Color_mesh_layer_4),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 65, 0, 0, kaguraoutfit1_Right_Forearm_mesh_layer_4),
								GEO_OPEN_NODE(),
									GEO_SWITCH_CASE(0, geo_switch_mario_hand),
									GEO_OPEN_NODE(),
										GEO_NODE_START(),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_ASM(0, geo_mario_hand_foot_scaler),
												GEO_SCALE(LAYER_FORCE, 65536),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kaguraoutfit1_Right_Hand_DL_mesh_layer_4),
												GEO_CLOSE_NODE(),
												GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_BRANCH(1, kaguraoutfit1_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1_jump_kaguraoutfit1_Mario_Right_Hand_Open_Armature),
										GEO_BRANCH(1, kaguraoutfit1_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1_jump_kaguraoutfit1_Mario_Right_Hand_Peace_Armature),
										GEO_BRANCH(1, kaguraoutfit1_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1_jump_kaguraoutfit1_Mario_Right_Hand_Cap_M_Logo_Armature),
										GEO_BRANCH(1, kaguraoutfit1_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1_jump_kaguraoutfit1_Mario_Right_Hand_Wing_Cap_Armature),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 13, -8, 42, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, kaguraoutfit1_Left_Thigh_Color_mesh_layer_4),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 89, 0, 0, kaguraoutfit1_Left_Leg_mesh_layer_4),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 67, 0, 0, kaguraoutfit1_Left_Foot_mesh_layer_4),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kaguraoutfit1_Left_Foot_mesh_layer_5),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 13, -8, -42, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, kaguraoutfit1_Right_Thigh_Color_mesh_layer_4),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 89, 0, 0, kaguraoutfit1_Right_Leg_mesh_layer_4),
						GEO_OPEN_NODE(),
							GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 67, 0, 0, 0, 0, 1),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
								GEO_OPEN_NODE(),
									GEO_ASM(2, geo_mario_hand_foot_scaler),
									GEO_SCALE(LAYER_FORCE, 65536),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kaguraoutfit1_Right_Foot_DL_mesh_layer_4),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kaguraoutfit1_Right_Foot_DL_mesh_layer_5),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kaguraoutfit1_2_LoD_Switch_opt0_Cap_Effect_Switch_opt2_jump_kaguraoutfit1_Mario_Cap_Off_Armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_ALPHA, kaguraoutfit1_Switch_Option_Head_Capless_DL_mesh_layer_4_mat_override_metal_0),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, kaguraoutfit1_Switch_Option_Head_Capless_DL_mesh_layer_1_mat_override_metal_0),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kaguraoutfit1_2_LoD_Switch_opt0_Cap_Effect_Switch_opt2_jump_kaguraoutfit1_Mario_Left_Hand_Open_Armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_ALPHA, 60, 0, 0, kaguraoutfit1_Switch_Option_Left_Hand_Open_mesh_layer_4_mat_override_metal_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kaguraoutfit1_2_LoD_Switch_opt0_Cap_Effect_Switch_opt2_jump_kaguraoutfit1_Mario_Right_Hand_Open_Armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_ALPHA, 60, 0, 0, kaguraoutfit1_Switch_Option_Right_Hand_Open_mesh_layer_4_mat_override_metal_0),
		GEO_OPEN_NODE(),
			GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kaguraoutfit1_2_LoD_Switch_opt0_Cap_Effect_Switch_opt2_jump_kaguraoutfit1_Mario_Right_Hand_Peace_Armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_ALPHA, 60, 0, 0, kaguraoutfit1_Switch_Option_Right_Hand_Peace_mesh_layer_4_mat_override_metal_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kaguraoutfit1_2_LoD_Switch_opt0_Cap_Effect_Switch_opt2_jump_kaguraoutfit1_Mario_Right_Hand_Cap_M_Logo_Armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, kaguraoutfit1_Switch_Option_Right_Hand_Cap_mesh_layer_1_mat_override_metal_0),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_ALPHA, kaguraoutfit1_Switch_Option_Right_Hand_Cap_mesh_layer_4_mat_override_metal_0),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kaguraoutfit1_2_LoD_Switch_opt0_Cap_Effect_Switch_opt2_jump_kaguraoutfit1_Mario_Right_Hand_Wing_Cap_Armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, kaguraoutfit1_Switch_Option_Right_Hand_Wing_Cap_mesh_layer_1_mat_override_metal_0),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_ALPHA, kaguraoutfit1_Switch_Option_Right_Hand_Wing_Cap_mesh_layer_4_mat_override_metal_0),
			GEO_DISPLAY_LIST(LAYER_ALPHA, kaguraoutfit1_Switch_Option_Right_Hand_Wing_Cap_Wings_mesh_layer_4_mat_override_metal_0),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kaguraoutfit1_2_LoD_Switch_opt0_Cap_Effect_Switch_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, kaguraoutfit1_Butt_mesh_layer_4_mat_override_metal_0),
			GEO_OPEN_NODE(),
				GEO_ASM(0, geo_move_mario_part_from_parent),
				GEO_ASM(0, geo_mario_tilt_torso),
				GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_ALPHA, 68, 0, 0, kaguraoutfit1_Torso_mesh_layer_4_mat_override_metal_0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 87, 0, 0, NULL),
						GEO_OPEN_NODE(),
							GEO_ASM(0, geo_mario_head_rotation),
							GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
							GEO_OPEN_NODE(),
								GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
								GEO_OPEN_NODE(),
									GEO_NODE_START(),
									GEO_OPEN_NODE(),
										GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_ALPHA, kaguraoutfit1_Head_DL_mesh_layer_4_mat_override_metal_0),
												GEO_DISPLAY_LIST(LAYER_OPAQUE, kaguraoutfit1_Head_DL_mesh_layer_1_mat_override_metal_0),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
									GEO_BRANCH(1, kaguraoutfit1_2_LoD_Switch_opt0_Cap_Effect_Switch_opt2_jump_kaguraoutfit1_Mario_Cap_Off_Armature),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_FORCE, 142, -51, 126, -15, 33, -133),
								GEO_OPEN_NODE(),
									GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
									GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_ALPHA, kaguraoutfit1_Left_Wing_DL_mesh_layer_4_mat_override_metal_0),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_FORCE, 142, -51, -126, 15, -33, -133),
								GEO_OPEN_NODE(),
									GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
									GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_ALPHA, kaguraoutfit1_Right_Wing_DL_mesh_layer_4_mat_override_metal_0),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 67, -10, 79, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, kaguraoutfit1_Left_Arm_Color_mesh_layer_4_mat_override_metal_0),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_ALPHA, 65, 0, 0, kaguraoutfit1_Left_Forearm_mesh_layer_4_mat_override_metal_0),
								GEO_OPEN_NODE(),
									GEO_SWITCH_CASE(1, geo_switch_mario_hand),
									GEO_OPEN_NODE(),
										GEO_NODE_START(),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_ASM(1, geo_mario_hand_foot_scaler),
												GEO_SCALE(LAYER_FORCE, 65536),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_ALPHA, kaguraoutfit1_Left_Hand_DL_mesh_layer_4_mat_override_metal_0),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_BRANCH(1, kaguraoutfit1_2_LoD_Switch_opt0_Cap_Effect_Switch_opt2_jump_kaguraoutfit1_Mario_Left_Hand_Open_Armature),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 68, -10, -79, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, kaguraoutfit1_Right_Arm_Color_mesh_layer_4_mat_override_metal_0),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_ALPHA, 65, 0, 0, kaguraoutfit1_Right_Forearm_mesh_layer_4_mat_override_metal_0),
								GEO_OPEN_NODE(),
									GEO_SWITCH_CASE(0, geo_switch_mario_hand),
									GEO_OPEN_NODE(),
										GEO_NODE_START(),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_ASM(0, geo_mario_hand_foot_scaler),
												GEO_SCALE(LAYER_FORCE, 65536),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_ALPHA, kaguraoutfit1_Right_Hand_DL_mesh_layer_4_mat_override_metal_0),
												GEO_CLOSE_NODE(),
												GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_BRANCH(1, kaguraoutfit1_2_LoD_Switch_opt0_Cap_Effect_Switch_opt2_jump_kaguraoutfit1_Mario_Right_Hand_Open_Armature),
										GEO_BRANCH(1, kaguraoutfit1_2_LoD_Switch_opt0_Cap_Effect_Switch_opt2_jump_kaguraoutfit1_Mario_Right_Hand_Peace_Armature),
										GEO_BRANCH(1, kaguraoutfit1_2_LoD_Switch_opt0_Cap_Effect_Switch_opt2_jump_kaguraoutfit1_Mario_Right_Hand_Cap_M_Logo_Armature),
										GEO_BRANCH(1, kaguraoutfit1_2_LoD_Switch_opt0_Cap_Effect_Switch_opt2_jump_kaguraoutfit1_Mario_Right_Hand_Wing_Cap_Armature),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 13, -8, 42, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, kaguraoutfit1_Left_Thigh_Color_mesh_layer_4_mat_override_metal_0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_ALPHA, 89, 0, 0, kaguraoutfit1_Left_Leg_mesh_layer_4_mat_override_metal_0),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_ALPHA, 67, 0, 0, kaguraoutfit1_Left_Foot_mesh_layer_4_mat_override_metal_0),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kaguraoutfit1_Left_Foot_mesh_layer_5_mat_override_metal_0),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 13, -8, -42, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, kaguraoutfit1_Right_Thigh_Color_mesh_layer_4_mat_override_metal_0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_ALPHA, 89, 0, 0, kaguraoutfit1_Right_Leg_mesh_layer_4_mat_override_metal_0),
						GEO_OPEN_NODE(),
							GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 67, 0, 0, 0, 0, 1),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
								GEO_OPEN_NODE(),
									GEO_ASM(2, geo_mario_hand_foot_scaler),
									GEO_SCALE(LAYER_FORCE, 65536),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_ALPHA, kaguraoutfit1_Right_Foot_DL_mesh_layer_4_mat_override_metal_0),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kaguraoutfit1_Right_Foot_DL_mesh_layer_5_mat_override_metal_0),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kaguraoutfit1_2_LoD_Switch_opt0_Cap_Effect_Switch_opt3_jump_kaguraoutfit1_Mario_Cap_Off_Armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kaguraoutfit1_Switch_Option_Head_Capless_DL_mesh_layer_4_mat_override_metal_0),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kaguraoutfit1_Switch_Option_Head_Capless_DL_mesh_layer_1_mat_override_metal_0),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kaguraoutfit1_2_LoD_Switch_opt0_Cap_Effect_Switch_opt3_jump_kaguraoutfit1_Mario_Left_Hand_Open_Armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, kaguraoutfit1_Switch_Option_Left_Hand_Open_mesh_layer_4_mat_override_metal_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kaguraoutfit1_2_LoD_Switch_opt0_Cap_Effect_Switch_opt3_jump_kaguraoutfit1_Mario_Right_Hand_Open_Armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, kaguraoutfit1_Switch_Option_Right_Hand_Open_mesh_layer_4_mat_override_metal_0),
		GEO_OPEN_NODE(),
			GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kaguraoutfit1_2_LoD_Switch_opt0_Cap_Effect_Switch_opt3_jump_kaguraoutfit1_Mario_Right_Hand_Peace_Armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, kaguraoutfit1_Switch_Option_Right_Hand_Peace_mesh_layer_4_mat_override_metal_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kaguraoutfit1_2_LoD_Switch_opt0_Cap_Effect_Switch_opt3_jump_kaguraoutfit1_Mario_Right_Hand_Cap_M_Logo_Armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, kaguraoutfit1_Switch_Option_Right_Hand_Cap_mesh_layer_1_mat_override_metal_0),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kaguraoutfit1_Switch_Option_Right_Hand_Cap_mesh_layer_4_mat_override_metal_0),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kaguraoutfit1_2_LoD_Switch_opt0_Cap_Effect_Switch_opt3_jump_kaguraoutfit1_Mario_Right_Hand_Wing_Cap_Armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, kaguraoutfit1_Switch_Option_Right_Hand_Wing_Cap_mesh_layer_1_mat_override_metal_0),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kaguraoutfit1_Switch_Option_Right_Hand_Wing_Cap_mesh_layer_4_mat_override_metal_0),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kaguraoutfit1_Switch_Option_Right_Hand_Wing_Cap_Wings_mesh_layer_4_mat_override_metal_0),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kaguraoutfit1_2_LoD_Switch_opt0_Cap_Effect_Switch_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, kaguraoutfit1_Butt_mesh_layer_4_mat_override_metal_0),
			GEO_OPEN_NODE(),
				GEO_ASM(0, geo_move_mario_part_from_parent),
				GEO_ASM(0, geo_mario_tilt_torso),
				GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 68, 0, 0, kaguraoutfit1_Torso_mesh_layer_4_mat_override_metal_0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 87, 0, 0, NULL),
						GEO_OPEN_NODE(),
							GEO_ASM(0, geo_mario_head_rotation),
							GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
							GEO_OPEN_NODE(),
								GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
								GEO_OPEN_NODE(),
									GEO_NODE_START(),
									GEO_OPEN_NODE(),
										GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kaguraoutfit1_Head_DL_mesh_layer_4_mat_override_metal_0),
												GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kaguraoutfit1_Head_DL_mesh_layer_1_mat_override_metal_0),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
									GEO_BRANCH(1, kaguraoutfit1_2_LoD_Switch_opt0_Cap_Effect_Switch_opt3_jump_kaguraoutfit1_Mario_Cap_Off_Armature),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_FORCE, 142, -51, 126, -15, 33, -133),
								GEO_OPEN_NODE(),
									GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
									GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kaguraoutfit1_Left_Wing_DL_mesh_layer_4_mat_override_metal_0),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_FORCE, 142, -51, -126, 15, -33, -133),
								GEO_OPEN_NODE(),
									GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
									GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kaguraoutfit1_Right_Wing_DL_mesh_layer_4_mat_override_metal_0),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 67, -10, 79, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, kaguraoutfit1_Left_Arm_Color_mesh_layer_4_mat_override_metal_0),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 65, 0, 0, kaguraoutfit1_Left_Forearm_mesh_layer_4_mat_override_metal_0),
								GEO_OPEN_NODE(),
									GEO_SWITCH_CASE(1, geo_switch_mario_hand),
									GEO_OPEN_NODE(),
										GEO_NODE_START(),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_ASM(1, geo_mario_hand_foot_scaler),
												GEO_SCALE(LAYER_FORCE, 65536),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kaguraoutfit1_Left_Hand_DL_mesh_layer_4_mat_override_metal_0),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_BRANCH(1, kaguraoutfit1_2_LoD_Switch_opt0_Cap_Effect_Switch_opt3_jump_kaguraoutfit1_Mario_Left_Hand_Open_Armature),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 68, -10, -79, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, kaguraoutfit1_Right_Arm_Color_mesh_layer_4_mat_override_metal_0),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 65, 0, 0, kaguraoutfit1_Right_Forearm_mesh_layer_4_mat_override_metal_0),
								GEO_OPEN_NODE(),
									GEO_SWITCH_CASE(0, geo_switch_mario_hand),
									GEO_OPEN_NODE(),
										GEO_NODE_START(),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_ASM(0, geo_mario_hand_foot_scaler),
												GEO_SCALE(LAYER_FORCE, 65536),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kaguraoutfit1_Right_Hand_DL_mesh_layer_4_mat_override_metal_0),
												GEO_CLOSE_NODE(),
												GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_BRANCH(1, kaguraoutfit1_2_LoD_Switch_opt0_Cap_Effect_Switch_opt3_jump_kaguraoutfit1_Mario_Right_Hand_Open_Armature),
										GEO_BRANCH(1, kaguraoutfit1_2_LoD_Switch_opt0_Cap_Effect_Switch_opt3_jump_kaguraoutfit1_Mario_Right_Hand_Peace_Armature),
										GEO_BRANCH(1, kaguraoutfit1_2_LoD_Switch_opt0_Cap_Effect_Switch_opt3_jump_kaguraoutfit1_Mario_Right_Hand_Cap_M_Logo_Armature),
										GEO_BRANCH(1, kaguraoutfit1_2_LoD_Switch_opt0_Cap_Effect_Switch_opt3_jump_kaguraoutfit1_Mario_Right_Hand_Wing_Cap_Armature),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 13, -8, 42, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, kaguraoutfit1_Left_Thigh_Color_mesh_layer_4_mat_override_metal_0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 89, 0, 0, kaguraoutfit1_Left_Leg_mesh_layer_4_mat_override_metal_0),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 67, 0, 0, kaguraoutfit1_Left_Foot_mesh_layer_4_mat_override_metal_0),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kaguraoutfit1_Left_Foot_mesh_layer_5_mat_override_metal_0),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 13, -8, -42, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, kaguraoutfit1_Right_Thigh_Color_mesh_layer_4_mat_override_metal_0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 89, 0, 0, kaguraoutfit1_Right_Leg_mesh_layer_4_mat_override_metal_0),
						GEO_OPEN_NODE(),
							GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 67, 0, 0, 0, 0, 1),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
								GEO_OPEN_NODE(),
									GEO_ASM(2, geo_mario_hand_foot_scaler),
									GEO_SCALE(LAYER_FORCE, 65536),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kaguraoutfit1_Right_Foot_DL_mesh_layer_4_mat_override_metal_0),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kaguraoutfit1_Right_Foot_DL_mesh_layer_5_mat_override_metal_0),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kaguraoutfit1_2_LoD_Switch_opt0_Cap_Effect_Switch_opt0_Hatless_Switch_opt0_Eye_Material_Switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_ALPHA, kaguraoutfit1_Head_DL_mesh_layer_4_mat_override_eyes_half_closed_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kaguraoutfit1_Head_DL_mesh_layer_1_mat_override_eyes_half_closed_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kaguraoutfit1_2_LoD_Switch_opt0_Cap_Effect_Switch_opt0_Hatless_Switch_opt0_Eye_Material_Switch_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_ALPHA, kaguraoutfit1_Head_DL_mesh_layer_4_mat_override_eyes_closed_2),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kaguraoutfit1_Head_DL_mesh_layer_1_mat_override_eyes_closed_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kaguraoutfit1_2_LoD_Switch_opt0_Cap_Effect_Switch_opt0_Hatless_Switch_opt0_Eye_Material_Switch_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_ALPHA, kaguraoutfit1_Head_DL_mesh_layer_4_mat_override_eyes_right_3),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kaguraoutfit1_Head_DL_mesh_layer_1_mat_override_eyes_right_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kaguraoutfit1_2_LoD_Switch_opt0_Cap_Effect_Switch_opt0_Hatless_Switch_opt0_Eye_Material_Switch_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_ALPHA, kaguraoutfit1_Head_DL_mesh_layer_4_mat_override_eyes_left_4),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kaguraoutfit1_Head_DL_mesh_layer_1_mat_override_eyes_left_4),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kaguraoutfit1_2_LoD_Switch_opt0_Cap_Effect_Switch_opt0_Hatless_Switch_opt0_Eye_Material_Switch_opt5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_ALPHA, kaguraoutfit1_Head_DL_mesh_layer_4_mat_override_eyes_up_5),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kaguraoutfit1_Head_DL_mesh_layer_1_mat_override_eyes_up_5),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kaguraoutfit1_2_LoD_Switch_opt0_Cap_Effect_Switch_opt0_Hatless_Switch_opt0_Eye_Material_Switch_opt6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_ALPHA, kaguraoutfit1_Head_DL_mesh_layer_4_mat_override_eyes_down_6),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kaguraoutfit1_Head_DL_mesh_layer_1_mat_override_eyes_down_6),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kaguraoutfit1_2_LoD_Switch_opt0_Cap_Effect_Switch_opt0_Hatless_Switch_opt0_Eye_Material_Switch_opt7[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_ALPHA, kaguraoutfit1_Head_DL_mesh_layer_4_mat_override_eyes_dead_7),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kaguraoutfit1_Head_DL_mesh_layer_1_mat_override_eyes_dead_7),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kaguraoutfit1_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SHADOW(1, 180, 100),
		GEO_OPEN_NODE(),
			GEO_SCALE(LAYER_FORCE, 16384),
			GEO_OPEN_NODE(),
				GEO_ASM(0, geo_mirror_mario_backface_culling),
				GEO_ASM(0, geo_mirror_mario_set_alpha),
				GEO_SWITCH_CASE(0, geo_switch_mario_stand_run),
				GEO_OPEN_NODE(),
					GEO_NODE_START(),
					GEO_OPEN_NODE(),
						GEO_SWITCH_CASE(0, geo_switch_mario_cap_effect),
						GEO_OPEN_NODE(),
							GEO_NODE_START(),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, kaguraoutfit1_Butt_mesh_layer_4),
									GEO_OPEN_NODE(),
										GEO_ASM(0, geo_move_mario_part_from_parent),
										GEO_ASM(0, geo_mario_tilt_torso),
										GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_ALPHA, 68, 0, 0, kaguraoutfit1_Torso_mesh_layer_4),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 87, 0, 0, NULL),
												GEO_OPEN_NODE(),
													GEO_ASM(0, geo_mario_head_rotation),
													GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
													GEO_OPEN_NODE(),
														GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
														GEO_OPEN_NODE(),
															GEO_NODE_START(),
															GEO_OPEN_NODE(),
																GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
																GEO_OPEN_NODE(),
																	GEO_NODE_START(),
																	GEO_OPEN_NODE(),
																		GEO_DISPLAY_LIST(LAYER_ALPHA, kaguraoutfit1_Head_DL_mesh_layer_4),
																		GEO_DISPLAY_LIST(LAYER_OPAQUE, kaguraoutfit1_Head_DL_mesh_layer_1),
																	GEO_CLOSE_NODE(),
																	GEO_BRANCH(1, kaguraoutfit1_2_LoD_Switch_opt0_Cap_Effect_Switch_opt0_Hatless_Switch_opt0_Eye_Material_Switch_opt1),
																	GEO_BRANCH(1, kaguraoutfit1_2_LoD_Switch_opt0_Cap_Effect_Switch_opt0_Hatless_Switch_opt0_Eye_Material_Switch_opt2),
																	GEO_BRANCH(1, kaguraoutfit1_2_LoD_Switch_opt0_Cap_Effect_Switch_opt0_Hatless_Switch_opt0_Eye_Material_Switch_opt3),
																	GEO_BRANCH(1, kaguraoutfit1_2_LoD_Switch_opt0_Cap_Effect_Switch_opt0_Hatless_Switch_opt0_Eye_Material_Switch_opt4),
																	GEO_BRANCH(1, kaguraoutfit1_2_LoD_Switch_opt0_Cap_Effect_Switch_opt0_Hatless_Switch_opt0_Eye_Material_Switch_opt5),
																	GEO_BRANCH(1, kaguraoutfit1_2_LoD_Switch_opt0_Cap_Effect_Switch_opt0_Hatless_Switch_opt0_Eye_Material_Switch_opt6),
																	GEO_BRANCH(1, kaguraoutfit1_2_LoD_Switch_opt0_Cap_Effect_Switch_opt0_Hatless_Switch_opt0_Eye_Material_Switch_opt7),
																GEO_CLOSE_NODE(),
															GEO_CLOSE_NODE(),
															GEO_BRANCH(1, kaguraoutfit1_Mario_Cap_Off_Armature),
														GEO_CLOSE_NODE(),
														GEO_TRANSLATE_ROTATE(LAYER_FORCE, 142, -51, 126, -15, 33, -133),
														GEO_OPEN_NODE(),
															GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
															GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
															GEO_OPEN_NODE(),
																GEO_DISPLAY_LIST(LAYER_ALPHA, kaguraoutfit1_Left_Wing_DL_mesh_layer_4),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
														GEO_TRANSLATE_ROTATE(LAYER_FORCE, 142, -51, -126, 15, -33, -133),
														GEO_OPEN_NODE(),
															GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
															GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
															GEO_OPEN_NODE(),
																GEO_DISPLAY_LIST(LAYER_ALPHA, kaguraoutfit1_Right_Wing_DL_mesh_layer_4),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 67, -10, 79, NULL),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, kaguraoutfit1_Left_Arm_Color_mesh_layer_4),
													GEO_OPEN_NODE(),
														GEO_ANIMATED_PART(LAYER_ALPHA, 65, 0, 0, kaguraoutfit1_Left_Forearm_mesh_layer_4),
														GEO_OPEN_NODE(),
															GEO_SWITCH_CASE(1, geo_switch_mario_hand),
															GEO_OPEN_NODE(),
																GEO_NODE_START(),
																GEO_OPEN_NODE(),
																	GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, NULL),
																	GEO_OPEN_NODE(),
																		GEO_ASM(1, geo_mario_hand_foot_scaler),
																		GEO_SCALE(LAYER_FORCE, 65536),
																		GEO_OPEN_NODE(),
																			GEO_DISPLAY_LIST(LAYER_ALPHA, kaguraoutfit1_Left_Hand_DL_mesh_layer_4),
																		GEO_CLOSE_NODE(),
																	GEO_CLOSE_NODE(),
																GEO_CLOSE_NODE(),
																GEO_BRANCH(1, kaguraoutfit1_Mario_Left_Hand_Open_Armature),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 68, -10, -79, NULL),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, kaguraoutfit1_Right_Arm_Color_mesh_layer_4),
													GEO_OPEN_NODE(),
														GEO_ANIMATED_PART(LAYER_ALPHA, 65, 0, 0, kaguraoutfit1_Right_Forearm_mesh_layer_4),
														GEO_OPEN_NODE(),
															GEO_SWITCH_CASE(0, geo_switch_mario_hand),
															GEO_OPEN_NODE(),
																GEO_NODE_START(),
																GEO_OPEN_NODE(),
																	GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, NULL),
																	GEO_OPEN_NODE(),
																		GEO_ASM(0, geo_mario_hand_foot_scaler),
																		GEO_SCALE(LAYER_FORCE, 65536),
																		GEO_OPEN_NODE(),
																			GEO_DISPLAY_LIST(LAYER_ALPHA, kaguraoutfit1_Right_Hand_DL_mesh_layer_4),
																		GEO_CLOSE_NODE(),
																		GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
																	GEO_CLOSE_NODE(),
																GEO_CLOSE_NODE(),
																GEO_BRANCH(1, kaguraoutfit1_Mario_Right_Hand_Open_Armature),
																GEO_BRANCH(1, kaguraoutfit1_Mario_Right_Hand_Peace_Armature),
																GEO_BRANCH(1, kaguraoutfit1_Mario_Right_Hand_Cap_M_Logo_Armature),
																GEO_BRANCH(1, kaguraoutfit1_Mario_Right_Hand_Wing_Cap_Armature),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 13, -8, 42, NULL),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, kaguraoutfit1_Left_Thigh_Color_mesh_layer_4),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_ALPHA, 89, 0, 0, kaguraoutfit1_Left_Leg_mesh_layer_4),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_ALPHA, 67, 0, 0, kaguraoutfit1_Left_Foot_mesh_layer_4),
													GEO_OPEN_NODE(),
														GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kaguraoutfit1_Left_Foot_mesh_layer_5),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 13, -8, -42, NULL),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, kaguraoutfit1_Right_Thigh_Color_mesh_layer_4),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_ALPHA, 89, 0, 0, kaguraoutfit1_Right_Leg_mesh_layer_4),
												GEO_OPEN_NODE(),
													GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 67, 0, 0, 0, 0, 1),
													GEO_OPEN_NODE(),
														GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
														GEO_OPEN_NODE(),
															GEO_ASM(2, geo_mario_hand_foot_scaler),
															GEO_SCALE(LAYER_FORCE, 65536),
															GEO_OPEN_NODE(),
																GEO_DISPLAY_LIST(LAYER_ALPHA, kaguraoutfit1_Right_Foot_DL_mesh_layer_4),
																GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kaguraoutfit1_Right_Foot_DL_mesh_layer_5),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_BRANCH(1, kaguraoutfit1_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1),
							GEO_BRANCH(1, kaguraoutfit1_2_LoD_Switch_opt0_Cap_Effect_Switch_opt2),
							GEO_BRANCH(1, kaguraoutfit1_2_LoD_Switch_opt0_Cap_Effect_Switch_opt3),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ASM(1, geo_mirror_mario_backface_culling),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kaguraoutfit1_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_ALPHA, kaguraoutfit1_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kaguraoutfit1_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
